### ISSUE TITLE
Picture light box

### ISSUE THREAD

**Issue by AndersonHJB** [catherineisonline/travel-with-catherine#1]
未来能否支持呢？这个项目很满足小白和旅行✈️爱好者的图片网站。

> Can it be supported in the future? This project is very satisfying for Xiaobai and travel ✈️ enthusiasts on the picture site.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/48122016/219854658-ccb19f9d-77d7-421b-ba18-aa4e304effd8.png">

**Comment by catherineisonline** [comment]
Yes
