### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by AndersonHJB** [catherineisonline/travel-with-catherine#2]
图片，我看您是使用指定图片名称，能否实现图片放入指定文件夹中，自动读取加载呢？这样貌似更加方便一些。

> I see that you are using the name of the specified picture. Can you put the picture into the specified folder and automatically read and load it? It seems more convenient.

**Comment by AndersonHJB** [comment]
我拍的照片，我也一直寻找这样的开源，我感觉你的很棒。

> I took the photos, I've also been looking for such open source, I think yours is great.

![DSC00823](https://user-images.githubusercontent.com/48122016/220810418-7cc9db98-56a9-4c5b-8efd-b43bc6c76196.JPG)

**Comment by catherineisonline** [comment]
I will check this project later, thank you for suggestions
