### ISSUE TITLE
Mobile phones don't work

### ISSUE THREAD

**Issue by AndersonHJB** [catherineisonline/travel-with-catherine#4]
![image](https://github.com/catherineisonline/travel-with-catherine/assets/48122016/de12f7dc-d632-46de-8ae5-44153ecc7027)

**Comment by AndersonHJB** [comment]
Can't the picture show the light box?

**Comment by AndersonHJB** [comment]
It appears that this project is not optimized for mobile devices. I am accessing it on my iPhone 13 Pro Max through Safari, and the display is not optimal. Here is a screenshot for your reference.
![image](https://github.com/catherineisonline/travel-with-catherine/assets/48122016/f6113f84-0067-421c-b83f-0f63a5f3df62)
![image](https://github.com/catherineisonline/travel-with-catherine/assets/48122016/131b8e25-842d-499d-8710-c1381466449a)
I apologize for any confusion. I did not design the layout of the project to appear as it does on your mobile device. It seems that there may be compatibility issues with the mobile platform and the project's design.

**Comment by AndersonHJB** [comment]
The term "lightbox" refers to an interactive feature that allows users to click on an image to enlarge it and view it in greater detail. You can see an example of this feature below.
<img width="1728" alt="image" src="https://github.com/catherineisonline/travel-with-catherine/assets/48122016/97bc0225-5a22-4994-9fbf-f29f012e8a1d">

**Comment by catherineisonline** [comment]
Thank you for specifying, I will update the mobile version. The lightbox was not supposed to be there from the very start. I did not intend to do it from the beginning but it's a good idea for sure. Thanks
