### ISSUE TITLE
Can the image option function be realized in the later stage?

### ISSUE THREAD

**Issue by AndersonHJB** [catherineisonline/travel-with-catherine#8]
Can the image option function be realized in the later stage?
Is similar to the back click on the picture, you can enter a pile of pictures, you can also choose whether there is copy.

https://github.com/catherineisonline/travel-with-catherine/assets/48122016/5cc0caee-553f-4201-b853-cbeda2e376d9

**Comment by catherineisonline** [comment]
> Can the image option function be realized in the later stage? Is similar to the back click on the picture, you can enter a pile of pictures, you can also choose whether there is copy.
> 
>  383_1713356700.mp4

I am not sure about implementing such features but I will keep it in mind. Thanks
